version: '3'
services:
  web:
    build: 
      context: ./back/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back:/app:cached
      #- bundle:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes: 
      - ./front:/app
      - /app/node_modules
    command: "yarn start-prd"
    ports:
      - 8080:8080